### PR TITLE
Added Change Role func.

### PR DESCRIPTION
**Pull request by AkshatSharma5**
issue - https://github.com/Web-Team-IITI-Gymkhana/tpc-frontend/issues/32 [User type switching from the profile section]
One remaining feature is that when user switches profile , his current role is updated in cookie also.
I'll be working on it shortly.

### CODE REVIEW

**Comment by AkshatSharma5** [comment]
image

**Comment by gjain-7** [comment]
Please also mention in your top comment to which issue this PR refer.

> but cookie update issue exist

What is the issue? mention this also is the top comment

**Comment by AkshatSharma5** [comment]
> Please also mention in your top comment to which issue this PR refer.
> 
> > but cookie update issue exist
> 
> What is the issue? mention this also in the top comment

It is this one - https://github.com/Web-Team-IITI-Gymkhana/tpc-frontend/issues/32  **[User type switching from the profile section #32]**

**Comment by web-team-iiti** [comment]
@AkshatSharma5 please resolve merge conflicts and we can remove package-lock file changes. use yarn

**Pull request closed without merging**
